### ISSUE TITLE
Implementation

### ISSUE THREAD

**Issue by julesmoretti** [scalyr/angular#17]
Hello There:

First of all thank you for sharing your directives, that is very exciting stuff as my project needs some serious optimizations and Scalyr seems very promising. Though upon integration I am running through some issues such as:

    ReferenceError: lhs is not defined
        at compile (http://127.0.0.1:9000/scalyr.js:579:15)
        at invokeLinkFn (http://127.0.0.1:9000/lib/angular/angular.js:8642:9)
        at nodeLinkFn (http://127.0.0.1:9000/lib/angular/angular.js:8142:11)
        at compositeLinkFn (http://127.0.0.1:9000/lib/angular/angular.js:7534:13)
        at nodeLinkFn (http://127.0.0.1:9000/lib/angular/angular.js:8137:24)
        at compositeLinkFn (http://127.0.0.1:9000/lib/angular/angular.js:7534:13)
        at publicLinkFn (http://127.0.0.1:9000/lib/angular/angular.js:7409:30)
        at compile (http://127.0.0.1:9000/lib/angular-ui-router/release/angular-ui-router.js:4026:9)
        at invokeLinkFn (http://127.0.0.1:9000/lib/angular/angular.js:8642:9)
        at nodeLinkFn (http://127.0.0.1:9000/lib/angular/angular.js:8142:11) 

I have added the script to the root folder as well as the folders that it came with and added 'sly' to my module dependencies, but is there anything else I am supposed to pass as a dependency to get the lhs error to disappear?

Thank you for the help and sorry for the burden.

**Comment by czerwingithub** [comment]
Hello -

You are tripping over a bug in our code that occurs when you do not
properly define the identifier in your sly-repeat expression.  The
expression should look like "foo in bar"  ... you have something like
"(groupName, groupData) in editSelection".  That form is not supported by
sly-repeat.

-Steve

**Comment by julesmoretti** [comment]
@czerwingithub got it. Thank you very much.

**Comment by julesmoretti** [comment]
@czerwingithub any chances of an update soon that includes the compatibility with "(groupName, groupData) in editSelection"?

Because at this point I am going to have to rewrite more then 40 entries and their related logics. So thought I would ask before I jump into it. :)

**Comment by julesmoretti** [comment]
Actually I will not be able to rewrite it as time is too short. So if you ever have an update coming up that would be awesome. Please let me know.

Thank you.

**Comment by czerwingithub** [comment]
Hi Jules -

Sorry, we don't plan any updates in the near future.  We aren't actively
maintaining this library.  We published to help demonstrate some concepts
and give folks a starting point.

-Steve

**Comment by julesmoretti** [comment]
@czerwingithub Got it thank you.
